version: "3.2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
      POSTGRES_DB: test-db
    ports:
      - 5432:5432
    networks:
      - docker-net

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
